### ISSUE TITLE
archian.sh requires arch-install.log to exist

### ISSUE THREAD

**Issue by Pr0xy5** [eb3095/archian#1]
arch-install.log is only created if archian.json exists (LOGGING="true"), this causes archian.sh to hard fail when trying to move this file.

Seems like a conditional statement needs to be added to line 132 of archian.sh to not try to move this file if logging is not true.

The Arch installation completes successfully but script ends when this error is received with no indication of completion.

Steps to reproduce:
1. Boot latest Arch ISO (archlinux-2021.04.01-x86_64.iso)
2. Execute web.sh
3. Select anything
4. After chroot script finishes the following error is received: `mv: cannot stat 'arch-install.log' : No such file or directory`

**Comment by eb3095** [comment]
Indeed. Added a file check for it. Thanks for the report!

Fixed in 2.4, new ISO's are built at 4am EST
